version: "3.9"
services:
  app:
    build: .
    container_name: maven_builder
    volumes:
      - app-volume:/opt/tomcat/webapps
    ports:
      - 8082:8080
  tomcat:
    restart: always
    image: tomcat:9-alpine
    container_name: tomcat
    volumes:
      - app-volume:/opt/tomcat/webapps
    ports:
      - 8083:8080

volumes:
  app-volume:

