version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/tmp
    ports:
      - 8000:8000
    image: app:maven
    container_name: maven_builder

  webbox:
    image: tomcat
    volumes:
      -./tmp/hello-1.0.war:/opt/tomcat/webapps/hello-1.0.war
    ports:
      - 8082:8080



