version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/tmp
    ports:
      - 8000:8000
    image: app:maven
    container_name: maven_builder

  web:
   image: tomcat:latest
   ports:
      - 8787:80
   volumes:
    - ./tmp:/opt/tomcat/webapps


