---
version: "2"
services:
  webservices:
    image: nginx:latest
    links:
      -php
    ports:
      -"8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      -php

